Repository UWC2-APIDOC/to-do-service-sp25, pull requests merged in 2025-07, with the labels that each got.

#159 Feature5.2
  postman/to-do-example_cristinalom.md
Labels: Assignment_5.2

#155 Assignment 5.2 to fix issue #54
  to-do-example_cjmoreno094.md
Labels: Assignment_5.2

#231 created a new Overview topic for the To-Do Service to fix issue #105
  docs/overviews/to-do-overview_tihsle.md
Labels: Assignment_6.1

#200 create get-users.md for homework 6.2
  docs/index.md
  docs/tutorials/get-users.md
Labels: Assignment_6.2

#181 Assignment 6.2
  docs/tutorials/user-id.md
Labels: Assignment_6.2

#215 create update-userid.md
  docs/api/update-userid.md
Labels: Assignment_6.3

#214 create a new reference topic about PATCH /users/{userID} to fix issue #142
  docs/api/update_user-by-id.md
Labels: Assignment_6.3

#190 Feature4 - API Reference for PATCH /tasks/{taskId} operation for Issue #143
  docs/api/update_task.md
Labels: InProgress, Assignment_6.3
